### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by IoNaNO** [IoNaNO/PalmRecoServer#3]
```bash
(palm) neo@LAPTOP-TK5KLJFB:~/Documents/PalmRecoServer$ python server.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1709912776.258660     154 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
^C^C^C^C^C^C^C^C^C^C^CINFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/home/neo/Documents/PalmRecoServer/server.py", line 27, in <module>
    detector = vision.HandLandmarker.create_from_options(options)
  File "/home/neo/miniconda3/envs/palm/lib/python3.9/site-packages/mediapipe/tasks/python/vision/hand_landmarker.py", line 364, in create_from_options
    return cls(
  File "/home/neo/miniconda3/envs/palm/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
KeyboardInterrupt
```

**Comment by IoNaNO** [comment]
The issue might stem from the WSL environment since the code works fine on an Ubuntu 22.04 server. Consider resolving it comprehensively by deploying the project using Docker.
